export const characters = [
  "Albedo",
  "Aloy",
  "Amber",
  "Arataki Itto",
  "Ayaka",
  "Ayato",
  "Barbara",
  "Beidou",
  "Bennett",
  "Chongyun",
  "Collei",
  "Diluc",
  "Diona",
  "Eula",
  "Fischl",
  "Ganyu",
  "Gorou",
  "Hutao",
  "Jean",
  "Kaeya",
  "Kazuha",
  "Keqing",
  "Klee",
  "Kokomi",
  "Kuki Shinobu",
  "Lisa",
  "Mona",
  "Ningguang",
  "Noelle",
  "Qiqi",
  "Raiden",
  "Razor",
  "Rosaria",
  "Sara",
  "Sayu",
  "Shenhe",
  "Shikanoin Heizou",
  "Sucrose",
  "Childe",
  "Thoma",
  "Tighnari",
  "Traveler Anemo",
  "Traveler Dendro",
  "Traveler Electro",
  "Traveler Geo",
  "Venti",
  "Xiangling",
  "Xiao",
  "Xingqiu",
  "Xinyan",
  "Yae Miko",
  "Yanfei",
  "Yelan",
  "Yoimiya",
  "Yunjin",
  "Zhongli",
];

export const typesOfWeapon = [
  { title: "Weapon", value: "" },
  { title: "Claymore", value: "Claymore" },
  { title: "Polearm", value: "Polearm" },
  { title: "Bow", value: "Bow" },
  { title: "Catalyst", value: "Catalyst" },
  { title: "Sword", value: "Sword" },
];

export const rarity = [
  { title: "Rarity", value: "" },
  { title: "4 star", value: "4 star" },
  { title: "5 star", value: "5 star" },
];

export const elements = [
  { title: "Elements", value: "" },
  { title: "Anemo", value: "Anemo" },
  { title: "Cryo", value: "Cryo" },
  { title: "Dendro", value: "Dendro" },
  { title: "Electro", value: "Electro" },
  { title: "Geo", value: "Geo" },
  { title: "Hydro", value: "Hydro" },
  { title: "Pyro", value: "Pyro" },
];

export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "What is this", url: "/" },
      { title: "Featured", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      {
        title: "Discord",
        url: "/https://discordapp.com/users/526682863756771339",
      },
      { title: "Github", url: "/https://github.com/SuaNgo" },
      { title: "Facebook", url: "/https://www.facebook.com/suango.0612/" },
    ],
  },
];
